backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "product"
    label: "Product"
    folder: "src/pages/products"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Product Image", name: product-image, widget: "product-image"}
      - {label: "Background Image", name: "background-image", widget: "background-image"}
  
  - name: "test"
    label: "Test"
    folder: "src/pages/products"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: image, widget: "image"}
      - file: "src/pages/environment/environment.md"
        label: "Environment"
        name: "environment"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "environment-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/environment"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Image, name: image, widget: image}